// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc190.frc2k16.subsystems;

import org.usfirst.frc190.frc2k16.RobotMap;
import org.usfirst.frc190.frc2k16.commands.*;

import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.Relay;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;

import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 *
 */
public class Collector extends Subsystem{

    private final SpeedController collectorActuationMotor = RobotMap.collectorcollectorActuationMotor;
    private final AnalogPotentiometer collectorPot = RobotMap.collectorcollectorPot;
    private final SpeedController collectorMotor = RobotMap.collectorcollectorMotor;

    public void initDefaultCommand() {
    	
    }
    
    public void stop(){
    	collectorMotor.set(0);
    }
    
    public void collect(){
    	collectorMotor.set(-1);
    }
    
    public void release(){
    	collectorMotor.set(1);
    }

}
