// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc190.GabeGoat.subsystems;

import org.usfirst.frc190.GabeGoat.Robot;
import org.usfirst.frc190.GabeGoat.RobotMap;
import org.usfirst.frc190.GabeGoat.commands.*;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveGabe extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController leftTalon = RobotMap.driveGabeLeftTalon;
    private final SpeedController rightTalon = RobotMap.driveGabeRightTalon;
    private final RobotDrive robotDrive21 = RobotMap.driveGabeRobotDrive21;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // Set the default command for a subsystem here.
    	//setDefaultCommand(new VisionTest());
        // setDefaultCommand(new MySpecialCommand());
    }

	public void forward() {
		// TODO Auto-generated method stub
		robotDrive21.arcadeDrive(.25, 0);
		
	}
	
	public void turn(double speed){
		robotDrive21.arcadeDrive(0,speed);
	}

	public void stop() {
		// TODO Auto-generated method stub
		robotDrive21.arcadeDrive(0, 0);
	}
	
	public void arcadeDrive(double speed, double angle) {
		RobotMap.driveGabeRobotDrive21.arcadeDrive(speed, angle);
	}
}

